### ISSUE TITLE
[XXL] Move A&R from Terraform to SAM

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#291] opened 2023-12-08 23:25 UTC
### Description
Goal is to be able to deploy A&R via SAM without the use of any terraform.

### Acceptance Criteria
- [x] Everything that is AWS side will need to be setup using SAM:
  - [x] Lambda
  - [x] API Gateway (and using an authorizer)
  - [x] Cloudformation
  - [x] DynamoDB
  - [x] Cloudwatch
  - [x] S3
- [x] All tests pass
- [ ] GitHub Actions deploys successfully to dev, test, prod
- [x] Terraform is completely removed
- [x] Old, non-SAM code is removed
- [x] Full smoke test to make sure everything ported over properly

#### Development Checklist:

- [x] All tests are converted to work with the SAM changes, this mean path changes and conversion(s) for layers
- [x] All tests run successfully and pass
- [x] Update READMEs accordingly

#### Dependencies

- Broken out into smaller tickets:
  - #322 
  - #323 
  - #342 
  - #343 

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

### Notes:
- pause any additional dev work on A&R while this is being worked on (unless it is an urgent bug)
- Related: #336 https://github.com/bcgov/parks-reso-api/issues/336

**Comment by JLWade** [comment] 2024-01-16 20:24
moving this out due to size and priority shifts

**Comment by Dianadec** [comment] 2024-03-19 17:10
@Christopher-walsh22 will update this ticket - break down into smaller pieces and add in any additional info based on the last similar ticket. cc @JLWade

**Comment by manuji** [comment] 2024-07-30 05:51
Tested on TEST: **Pending**

While performing the regression testing, the following issues were seen;

1. Console errors when navigating to the Export report page. 


![Image](https://github.com/user-attachments/assets/a3051646-032e-4272-ba55-29850c1f7af0)

2. Issue with the user permissions -> If I am only assigned with access to one or more parks, I can still see the other park names in the Enter data dropdown and I can save records with data to those other parks. (no issue with the Exported report, it only shows the data for the assigned park/sub area)



https://github.com/user-attachments/assets/053be411-7660-4919-b859-c8953b710d9a

3. Issue with the Variances; no variance warnings triggered on Enter data pages. 
4. Exporting reports takes longer than usual (About 2 minutes or more)

FYI @davidclaveau & @Christopher-walsh22

**Comment by manuji** [comment] 2024-07-31 04:43
@Christopher-walsh22  & @davidclaveau , my test to see if the park names get updated from the Data register has been failed. I changed the park name "Strathcona Park" to be "Strathcona Park - BC" refer here: https://alpha-test.bcparks.ca/strathcona-park/ on test environment, but that name update has not been reflected on A&R- TEST.

**Comment by davidclaveau** [comment] 2024-07-31 18:51
Thanks @manuji for the testing! We've update Dev with the fixes, so you can move Dev into Test whenever you find the time.

@Chris and I have fixes/explanations for all items listed in your findings. Here's the list of our fixes:

> 1. Console errors when navigating to the Export report page.
- Chris found this error in the `public` client, so a fix will be rolled out later today.

> 2. Issue with the user permissions
- Fix is now applied in the `api`. There was a funny issue where our Local and Tools was parsing the `permissionObejct` properly, so that's why we didn't see the same error in the bulk of our testing. In Dev and Test, however, the `permissionObject` was coming through as strings. Quick change to how we parse `permissionObject` and it properly converts everything over and will only show parks for their respective roles. 

> 3. Issue with the Variances; no variance warnings triggered on Enter data pages.
- This was actually an issue in the data entered for the variance record. I didn't know this, but if you add anything to the Notes section in the record, it won't flag it as a _variance record_ and apply that red box on the Enter Data page. The Notes section had "test123" or something similar before, and after I deleted it and saved the changes the "Variance" red box appeared again. The record I tested:
- 2024/07 
- Strathcona
- Buttle Lake
- Frontcountry Camping
![Image](https://github.com/user-attachments/assets/0f8ad1d7-26e5-4f1d-aadf-9df621ae4b74)

> 4. Exporting reports takes longer than usual (About 2 minutes or more)
- I took a look at the export function and how we parse the data and get the export into our S3 bucket. Beyond the AWS SDK V3 updates, we didn't make any sweeping changes so I think the exporter will just take a bit longer now.

> 5. my test to see if the park names get updated from the Data register has been failed.
- This is fixed as well! There was a missing cronjob on the nameUpdate, and the function was also set to timeout too quickly (taking on the global timeout of 3s); it should properly run now at 8am PDT every day, or I can manually invoke it in AWS for immediate changes and make sure things are coming through.

The Checks for Tests and Trivy Analysis should be passing now as well.

Let us know if you have any questions!

**Comment by manuji** [comment] 2024-08-01 08:19
Hi @davidclaveau I really appreciate your detailed report about the fixes. Thank you very much. I will deploy the latest to test and verify the bug fixes and will let you know if there is anything we need further investigation.

**Comment by manuji** [comment] 2024-08-06 14:38
Hi @Christopher-walsh22 I see that the above mentioned PR is not merged to the Admin repo yet, do you happen to know if this PR has the fix for the issue with Park name update? I still don't see the updated Park name on the A&R-Admin.

**Comment by Christopher-walsh22** [comment] 2024-08-06 17:00
@manuji Just got the missing review for the PR. It has now been merged. This wont fix the issue for the park name update, but it does resolve the console warning you mentioned from TEST1.

**Comment by manuji** [comment] 2024-08-06 17:08
@Christopher-walsh22 , I will move this to do to check the issue with updating the park names from the Data register.

**Comment by davidclaveau** [comment] 2024-08-07 15:37
@manuji I was able to find the issue with the Park name update, and it was a simple but silly typo on my part. I've added the update to Dev now, so it should be good to move to Test shortly.

During the debugging I made some changes to Test, so Test is currently showing the correct park name only because of my manual changes. Once A&R is moved to Test, you can change the name again in DR and I'll trigger the Name Update function and we should see the name update as expected.

Some good news is that there were logs showing that the cronjob was running at 8am as expected, but it was just failing due to that typo.

Apologies for the re-deploy!

**Comment by manuji** [comment] 2024-08-07 17:04
Hi @davidclaveau , I would like to run the cronjob myself if that's possible, I knew how to do it before this SAM update, if you could give access and instructions about anything that has changed from what we had before, I should be able to manage it :) Thank for fixing the issue.

**Comment by davidclaveau** [comment] 2024-08-07 17:38
Sent you a message in Teams 😁

**Comment by manuji** [comment] 2024-08-07 18:23
Tested on TEST: Passed
* Verified that this is good to go to PROD. 
* Passing to PO review. 

Thank you @davidclaveau for the support!

**Comment by meyerdarcie** [comment] 2024-08-07 19:02
This ticket is complete/bugs sorted out - moving to done. As per @manuji, final review of A&R to be completed prior to deploying to prod.

**Closed by meyerdarcie** 2024-08-07 19:02 UTC
Labels: A&R, terraform
