### ISSUE TITLE
[S] A&R: Change Section for Alexandra Bridge park

### ISSUE THREAD

**Issue by JLWade** [bcgov/bcparks-ar-api#332] opened 2024-05-13 20:50 UTC
#### Description:

for Alexandra Bridge Park (0330) change its Section from Thompson Cariboo to Lower Mainland.

#### Acceptance Criteria:

- [ ] 0330 Alexandra Bridge (and all subareas) section is changed to "Lower Mainland"
  - [ ] This is shown in exported report 

#### Development Checklist:

- [ ] Migration will need to be run (only on prod so that we can move this forward) to change all records in A&R

#### Dependencies

- Blocked by 
- Blocking

**Relevant documentation as reference**

**Definition of Ready**

- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if applicable)
- [ ] Design / Solution is accepted by Product Owner (if applicable)
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by marklise** [comment] 2024-06-13 21:11
Requires migration to run once deployed to test/prod

**Comment by manuji** [comment] 2024-06-27 01:00
Hi @marklise , this has been deployed to TEST environment, could you please run the migration on TEST environment? Thanks in advance!

**Comment by marklise** [comment] 2024-06-28 17:37
@manuji This has been deployed to TEST.

**Comment by manuji** [comment] 2024-06-28 18:11
Thank you @marklise

**Comment by manuji** [comment] 2024-07-04 16:45
Verified that the requested change has been done from the DynamoDB. Pending testing the Exported report. 

Blocked by: https://github.com/bcgov/bcparks-ar-api/issues/326

**Comment by Dianadec** [comment] 2024-07-09 16:50
Note: A&R SAM stuff will fix the export issue. cc @manuji

**Comment by manuji** [comment] 2024-07-12 21:52
Tested on PROD: 
* verified that this change request has been done using DynamoDB PROD instance. 
*

**Comment by meyerdarcie** [comment] 2024-07-19 15:25
Working as intended, moving to done.

**Closed by meyerdarcie** 2024-07-19 15:25 UTC
Labels: A&R, Data Change
